### ISSUE TITLE
Поправить стили

### ISSUE THREAD

**Issue by ninedev-i** [Grads521/Game#18]
Ты прописываешь шрифт для каждого компонента, в то время как достаточно прописать tего в * {}

Зачем ты импортируешь дополнительный шрифт boldGeometria я не понимаю.

Плюс у тебя какая-то беда с пустыми строчками, которые повсюду.

**Comment by Grads521** [comment]
Хотелось сделать два шрифта. Для ответов и кнопок один. А для остального жирный. Поэтому два. А через *. Он же будет один для всех?
