### ISSUE TITLE
Добавить валидацию выбора ответа

### ISSUE THREAD

**Issue by Grads521** [Grads521/Game#4]

**Comment by ninedev-i** [comment]
мы не должны иметь возможность перейти к следующему вопросу, пока не ответили на текущий

**Comment by Grads521** [comment]
Нужно через if задать условие, что если кнопка checked. То событие функция accept выполняется как обычно. А если нет, то выскакивает ошибка, может какой нить alert

**Comment by ninedev-i** [comment]
+

**Comment by ninedev-i** [comment]
> Нужно через if задать условие, что если кнопка checked. То событие функция accept выполняется как обычно. А если нет, то выскакивает ошибка, может какой нить alert

да
